<a href="https://colab.research.google.com/github/Heet131024/PDF-Merger/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resources notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## introduction to Tensors

### Creating Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# get tensor back as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7 , 8] , [9 , 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1 , 2 , 3], [6 , 9 , 12],[15 , 18 , 21]], [[24 , 27 , 30] , [33 , 36 , 39] , [42 , 45 , 48]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 6,  9, 12],
         [15, 18, 21]],

        [[24, 27, 30],
         [33, 36, 39],
         [42, 45, 48]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([2, 3, 3])

In [26]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 6,  9, 12],
        [15, 18, 21]])

In [29]:
TENSOR[1]


tensor([[24, 27, 30],
        [33, 36, 39],
        [42, 45, 48]])

## Random Tensors

###Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

###Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [37]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7416, 0.6791, 0.8605, 0.6564],
        [0.3970, 0.1883, 0.7383, 0.2413],
        [0.3354, 0.4734, 0.2866, 0.5448]])

In [38]:
random_tensor.ndim

2

In [42]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3 , 224 , 224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)